### ISSUE TITLE
[Tracking] Things needed to be done

### ISSUE THREAD

**Issue by geminateCoder** [geminateCoder/Character-Archive-Website#1]
## TODO
- [ ] Template for index/home page.
- [ ] Forms for login and register.
- [ ] Connect DB with forms using Flask-WTF.
- [ ] Dashboard Template
